### PR TITLE
Scancode set1

### PR DESCRIPTION
**Pull request by ZerothLaw**
Had to do some more refactoring, sorry. The state logic is different for scancode set 1 compared to set 2.

### CODE REVIEW

**Comment by thejpster** [comment]
I've put a Travis CI file in master. Could you merge it into your branch? We can then see if the tests work before I merge this. Thanks!

**Comment by ZerothLaw** [comment]
Just done!

**Comment by thejpster** [comment]
Thanks!

**Comment by thejpster** [comment]
v0.3.0 released.

**Pull request merged**
