### PR TITLE
Two fixes for scancode set 1

### PR DESCRIPTION
**Pull request by phil-opp**
This PR updates the scancode set 1 state machine to make the `Release` and `ExtendedRelease` states equivalent to the `Start` state. Before, a `clear` call was required after each KeyEvent, because the `Release` and `ExtendedRelease` state were forever looping.

It also fixes a bug in the new scancode 1 implementation where a decimal `80` was subtracted instead of a hexadecimal `0x80`. This fixes the issue that the KeyUp event of the shift key was not recognized so that the input stayed uppercase forever.

This PR also removes some trailing whitespace and runs rustfmt. This is of course optional and I can remove it if it's not wanted.

cc @ZerothLaw

### CODE REVIEW

**Comment by phil-opp** [comment]
Seems like I broke some tests. I will look into it…

**Comment by phil-opp** [comment]
Ok, seems like changing the state machine for scancode set 2 was the problem. I updated the PR to only apply the fixes for scancode set 1.

**Comment by ZerothLaw** [comment]
Thanks for finding that issue!

**Comment by phil-opp** [comment]
@thejpster Thanks! Could you release a new crates.io version with these fixes?

**Comment by phil-opp** [comment]
I consider this PR a bugfix, so I would probably bump the `y`. But I'm also fine with bumping the `x`.

**Comment by thejpster** [comment]
Done

**Pull request merged**
